name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-14
    env:
      SDL_VERSION: 2.28.5
    steps:
    #- name: Checkout
    #  uses: actions/checkout@v3
    #  with:
    #    submodules: recursive
    - name: Setup SDL2 frameworks
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: ${{ env.SDL_VERSION }}
        dest: "${{ env.$GITHUB_WORKSPACE}}/SDL2_macos"
    # - name: Build engine
    #  run: bash scripts/gha/build_macos.sh
#    - name: configure
#      run: python3 ./waf configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
      
