name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-14
    env:
      SDL_VERSION: 2.28.5
    steps:
    - name: Checkout
      uses: actions/checkout
      with:
        submodules: recursive
    - name: Setup SDL2 frameworks
      uses: BrettDong/setup-sdl2-frameworks@main
      with:
        sdl2: ${{ env.SDL_VERSION }}
        # dest: ${{ github.workspace }}/SDL2_macos
    - name: configure
      run: python3 ./waf configure --sdl2=${{ github.workspace }}/../../../Library/Frameworks/SDL2.framework -T release
    - name: build
      run: python3 ./waf build
    - name: install
      run: python3 ./waf install --destdir=artifacts
    - name: Upload engine (artifacts)
      uses: actions/upload-artifact
      with:
        name: artifact
        path: artifacts/*
